### ISSUE TITLE
Dict with Cython functions

### ISSUE THREAD

**Issue by sterinaldi** [sterinaldi/parametric#1]
Is there a way to make [this dict](https://github.com/sterinaldi/parametric/blob/2a36c0fe05c0fa144c3093f7797ecd26050aa318/parest/models.pyx#L274) with Cython functions? I'd like to import it in loglikelihood.pyx

**Comment by wdpozzo** [comment]
Yes, like this (see https://stackoverflow.com/questions/23304237/how-to-access-an-enum-type-by-value-in-cython)
